name: Update README with recent blog posts

on:
  schedule:
    - cron: '0 0 * * *'  # daily at 00:00 UTC
  workflow_dispatch: {}

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: |
          python scripts/update_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md README-zh.md || true
          git commit -m "chore: update recent blog posts" || echo "No changes to commit"
          git push origin HEAD:main || echo "Push failed"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
